env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  RNG: readonly
  PIXI: readonly
  Sim: readonly
  UI: readonly
  Agent: readonly
parserOptions:
  ecmaVersion: 2018
ignorePatterns:
  - lib/*
  - node_modules/
rules:
  func-names:
    - error
  no-underscore-dangle:
    - off
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-param-reassign:
    - error
    - props: false
